server:
  port: 8092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      reply-timeout: 10000
      receive-timeout: 10000
      retry:
        enabled: true
        max-attempts: 3